# Libraries
import json

# Main code
def lambda_handler(event, context) -> dict:
    """
    Main lambda function generated by default.

    :param event: The data from the event that triggered the function
    :param contex: The data about the execution environment of the function
    :param return: json body and status code
    """
    pass