name: Upload files
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'lambdas/**'
      - '.github/workflows/**'
jobs:
  main:
    name: Deploy lambdas
    runs-on: ubuntu-latest
    steps:
      # Checkout this repository
      - name: Checkout repo
        uses: actions/checkout@v2

      # Zip lambda folders
      - name: Zip lambda folders
        run: |
          zip -r lambda_gastos.zip lambdas/lambda_gastos
        
      # Upload lambda gastos
      - name: Upload lambda gastos
        uses: appleboy/lambda-action@master
        with:
          aws_region: eu-west-3
          aws_access_key_id: ${{ secrets.S3_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_KEY }}
          function_name: lambda_gastos
          zip_file: lambda_gastos.zip
