name: Upload files
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/lambda_gcalendar/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'lambdas/lambda_gcalendar/**'
      - '.github/workflows/**'
jobs:
  main:
    name: Upload lambda gastos
    runs-on: ubuntu-latest
    steps:
      # Checkout this repository
      - name: Checkout repo
        uses: actions/checkout@v2

      # Zip lambda folders
      - name: Zip lambda folders
        working-directory: lambda_gcalendar
        run: |
          zip -r ../lambda_gcalendar.zip .
        
      # Upload lambda gastos
      - name: Upload lambda gastos
        uses: appleboy/lambda-action@master
        with:
          aws_region: eu-west-3
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_KEY_SECRET }}
          function_name: lambda_gcalendar
          zip_file: lambdas/lambda_gcalendar.zip